blank_issues_enabled: false
contact_links:
  - name: "Propose a new Feature"
    url: https://github.com/withastro/rfcs/discussions
    about: Propose and discuss future improvements to Astro
  - name: "Submit an RFC"
    url: https://github.com/withastro/rfcs/pulls
    about: Submit an official RFC for an accepted feature proposal
  - name: ğŸ‘¾ Chat
    url: https://astro.build/chat
    about: Our Discord server is active, come join us!
  - name: ğŸ’ Support
    url: https://astro.build/chat
    about: "This issue tracker is not for support questions. Join us on Discord for assistance!"
